Post deploy smoke test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -184,3 +184,37 @@ jobs:
           heroku_app_name: "samples-test-spring-develop"
           heroku_email: ${{secrets.HEROKU_MY_USERNAME}}
           usedocker: true
+
+  deploy-test:
+    needs: [deploy]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v2
+        with:
+          distribution: 'temurin'
+          java-version: '8'
+          cache: 'maven'
+
+      #La configuracion para este test se hace con chrome headless contra la aplicacion desplegada
+      - name: Test configuration
+        run: |
+          echo "remote.web.driver.url=headless" > samples-test-spring.properties
+          echo "application.url=https://samples-test-spring-develop.herokuapp.com" >> samples-test-spring.properties
+
+      #Ejecuta maven solo para este test, controlando los fallos
+      #ojo, al especificar un unico test, maven lo ejecuta en la fase test aunque este en it!!!
+      - name: Build and test
+        run: mvn test -Dtest=TestPostDeploy -Dassembly.skipAssembly=true -Dmaven.test.failure.ignore=false
+      - if: failure()
+        run: mvn test -Dmaven.test.skip=true -Dassembly.skipAssembly=true && echo "Exit with error" && exit 1
+
+      #Publica reports
+      - if: always()
+        name: Publish test reports
+        uses: actions/upload-artifact@v2
+        with:
+          name: deploy-test-reports
+          path: |
+            target/surefire-reports/
+            target/site/
