Bump dependency versions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,8 +43,13 @@ jobs:
             aerokube/selenoid:latest-release
           docker logs selenoid
 
+      #Ejecuta maven haciendo que falle si fallan los tests
+      #Como esto no generara reports, en caso de fallo rejecuta maven sin los tests para poder gnerarlos
       - name: Build and test
-        run: mvn verify
+        run: mvn verify -Dmaven.test.failure.ignore=false
+      - if: failure()
+        name: Try test report generation after failure
+        run: mvn verify -Dmaven.test.skip=true -Dassembly.skipAssembly=true && echo "Exit with error" && exit 1
 
       - if: always()
         name: Selenoid stop
@@ -149,3 +154,9 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=my:samples-test-spring -Dsonar.organization=giis
+      - name: SonarQube Quality Gate check
+        uses: sonarsource/sonarqube-quality-gate-action@master
+        # Force to fail step after specific time
+        timeout-minutes: 5
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
